### ISSUE TITLE
Tile option

### ISSUE THREAD

**Issue by PopBogdan97** [rahra/smrender#6]
Hi, 
I was trying to use Smrender to generate PNG tiles in order to use them on a "navigator". So I changed the rules ad at the beginning all seems to work fine. But then, when I start looking to the various tiles, I noticed that as the zoom increases the details remain the same, you are only zooming the A4/A0 map. So I don't understand from the Documentation if this is the wanted behaviour or if the tiling mode should output a tiling map like Mapnik where by zooming you have more details.

Another issue I noticed, is that even with the "How To" example in the Documentation when processing higher zoom tiles like 18-20, the process ends giving a message "killed"

**Comment by rahra** [comment]
Well, the tiling option actually was just implemented as an experimental feature and that is what it still is.
Smrender was from beginning designed to render paper charts which obviously do not have zoom levels. The tile option just cuts to the chart into pieces which was rendered according to the ruleset. To properly reflect different zoom levels the ruleset would have to be adjusted as well.

To be honest, if you want to generate a typical slippy map with tiles for online use I would suggest to use a different renderer which was designed to do that. Smrender isn't the right choice for this purpose.
